[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = ["cd Backend && mvn clean install -DskipTests"]

[phases.start]
cmd = "cd Backend && java -Dserver.port=$PORT -jar target/portfolio-backend-1.0.0.jar"
